version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: event_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: event_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - event_management_network

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_management_app
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: event_management
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - event_management_network
    command: npm run start:dev

  # Redis (Optional - for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: event_management_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - event_management_network

volumes:
  postgres_data:

networks:
  event_management_network:
    driver: bridge

